home/urls.py
from django.urls import re_path

from . import views
from mwd.settings import STAGE

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^portfolio/$', views.portfolio, name='portfolio'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    re_path(r'^sites/$', views.sites, name='sites'),
    re_path(r'^sites/reorder/$', views.reorder_sites, name='reorder-sites'),
    re_path(r'^sites/add/$', views.add_site, name='add-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/edit/$', views.edit_site, name='edit-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete/$', views.delete_site, name='delete-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete-screenshot/(?P<screenshot_id>[1-9]\d*)/$', views.delete_screenshot, name='delete-screenshot'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete-screenshots/$', views.delete_screenshots, name='delete-screenshots'),
]

if STAGE != 'production':
    urlpatterns += [
        re_path(r'^400/$', views.view_400),
        re_path(r'^403/$', views.view_403),
        re_path(r'^404/$', views.view_404),
        re_path(r'^500/$', views.view_500),
    ]

mwd/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500,
)
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^legal/', include(('legal.urls', 'legal'), namespace='legal')),
    re_path(r'^quote/', include(('quotes.urls', 'quotes'), namespace='quotes')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'home.views.view_400'
handler403 = 'home.views.view_403'
handler404 = 'home.views.view_404'
handler500 = 'home.views.view_500'

home/forms.py
from django import forms

from .models import Site

class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(BaseForm, self).__init__(*args, **kwargs)

class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(BaseModelForm, self).__init__(*args, **kwargs)

class SiteForm(BaseModelForm):
    name = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Site Name',
        }),
    )
    url = forms.CharField(
        label='',
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'URL',
        }),
    )
    github = forms.CharField(
        label='',
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'value': 'https://github.com/McCarthyCode/',
            'placeholder': 'GitHub URL',
        }),
    )
    active = forms.BooleanField(
        initial=True,
        required=False,
        label='Website Is Active',
        widget=forms.CheckboxInput()
    )
    description = forms.CharField(
        label='',
        max_length=200,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Description',
            'rows': 5,
        }),
    )
    screenshots = forms.ImageField(
        label='Screenshots',
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )

    def clean(self):
        super().clean()
        return self.cleaned_data

    class Meta:
        model = Site
        fields = ['name', 'url', 'github', 'active', 'description']

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import (
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseRedirect,
)
from django.shortcuts import render, redirect, reverse, get_object_or_404

from .forms import SiteForm
from .models import Site, Screenshot
from .recaptcha import verify_v3

def view_400(request, exception=None):
    return render(request, 'errors/400.html', status=400)

def view_403(request, exception=None):
    return render(request, 'errors/403.html', status=403)

def view_404(request, exception=None):
    return render(request, 'errors/404.html', status=404)

def view_500(request, exception=None):
    return render(request, 'errors/500.html', status=500)

def index(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/index.html')

def legal(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'legal/index.html')

def login_view(request):
    if request.method == 'GET':
        if request.user.is_superuser:
            messages.info(request, 'You are already logged in. You have been redirected to the dashboard.')

            return redirect('home:dashboard')

        return render(request, 'home/login.html')
    elif request.method == 'POST':
        api_response = verify_v3(request)
        api_response_content = json.loads(str(api_response.content, encoding='utf-8'))

        if not api_response_content['success'] or api_response.status_code != 200:
            messages.error(request, 'There was an error with reCAPTCHA v3.')

            return redirect('quotes:index')

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)

            messages.success(request, 'Welcome, %s!' %
                (user.first_name if user.first_name else user.username)
            )

            return redirect('home:dashboard')
        else:
            messages.error(request, 'There was an error logging in with that username/password combination.')

            return redirect('home:login')
    else:
        return HttpResponseBadRequest()

def logout_view(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    logout(request)

    messages.success(request, 'You have successfully logged out.')

    return redirect('home:login')

def portfolio(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    sites = []
    for site in Site.objects.all().order_by('order'):
        sites.append({
            'data': site,
            'screenshots': Screenshot.objects.filter(site=site).order_by('date_updated'),
        })

    return render(request, 'home/portfolio.html', {'sites': sites})

def about(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/about.html')

def dashboard(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/dashboard.html')

def sites(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/sites.html', {
        'sites': Site.objects.all().order_by('order'),
    })

def reorder_sites(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'POST':
        return HttpResponseBadRequest()

    order = json.loads(request.POST.get('order'))

    position = 0
    for site_id in order:
        site = get_object_or_404(Site, id=site_id)
        if site.order != position:
            site.order = position
            site.save()
        position += 1

    return render(request, 'home/sites.html', {
        'sites': Site.objects.all().order_by('order'),
    })

def add_site(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == 'GET':
        return render(request, 'home/add_site.html', {
            'form': SiteForm(),
        })
    elif request.method == 'POST':
        form = SiteForm(request.POST, request.FILES)

        if form.is_valid():
            site = form.save()

            for image in request.FILES.getlist('screenshots'):
                screenshot = Screenshot.create(image=image, site=site)
                screenshot.save()

            messages.success(request, 'You have successfully added "%s."' % site.name)

            return redirect('home:sites')

        messages.error(request, 'There was an error adding a site.')

        return redirect('home:add-site')

    return HttpResponseBadRequest()

def edit_site(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    site = get_object_or_404(Site, id=site_id)

    if request.method == 'GET':
        return render(request, 'home/edit_site.html', {
            'site': site,
            'screenshots': Screenshot.objects.filter(site=site).order_by('date_updated'),
            'form': SiteForm(instance=site),
        })
    elif request.method == 'POST':
        form = SiteForm(request.POST, request.FILES, instance=site)

        if form.is_valid():
            site = form.save()

            order = json.loads(request.POST.get('order'))

            for screenshot_id in order:
                screenshot = get_object_or_404(Screenshot, id=screenshot_id)
                screenshot.save()

            for image in request.FILES.getlist('screenshots'):
                screenshot = Screenshot.create(image=image, site=site)
                screenshot.save()

            messages.success(request, 'You have successfully edited "%s."' % site.name)

            return redirect('home:sites')

        messages.error(request, 'There was an error editing the site.')

        return HttpResponseRedirect(
            reverse('home:edit-site', args=[site_id])
        )

    return HttpResponseBadRequest()

def delete_site(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    site.delete()

    messages.success(request, 'You have successfully deleted "%s" and its corresponding screenshots.' % site.name)

    return redirect('home:sites')

def delete_screenshot(request, site_id, screenshot_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    screenshot = get_object_or_404(Screenshot, id=screenshot_id)

    assert site == screenshot.site

    screenshot.delete()

    messages.success(request, 'Screenshot successfully deleted.')

    return HttpResponseRedirect(
        reverse('home:edit-site', args=[site_id])
    )

def delete_screenshots(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    site.delete_screenshots()

    messages.success(request, 'Screenshots successfully deleted.')

    return HttpResponseRedirect(
        reverse('home:edit-site', args=[site_id])
    )

home/templates/global/footer.html
  <footer id="footer">
    <div class="container">
      <div class="footer-list">
        <ul>
          <li>
            <small><a href="{% url 'legal:index' %}">Terms & Privacy</a></small>
          </li>
          <li>
            <small>{% if request.user.is_superuser %}<a href="{% url 'home:logout' %}">Logout</a>{% else %}<a href="{% url 'home:login' %}">Admin Login</a>{% endif %}</small>
          </li>
          <li>
            <small><a class="external-link" href="https://github.com/McCarthyCode/McCarthy-Code">GitHub</a></small>
          </li>
        </ul>
      </div>
      <p>
        <small><span class="text-nowrap">&copy; {{ year }} <span class="brand"></span>. <a href="https://github.com/McCarthyCode/McCarthy-Code/blob/master/LICENSE.md" class="external-link">MIT Licensed</a>.</span></small>
      </p>
      <p>
        <small>Icons by <a href="https://fontawesome.com/" class="external-link">Font Awesome</a>.</small>
      </p>
    </div>
  </footer>

home/templates/global/navbar.html
  <nav id="navbar" class="navbar fixed-top navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home:index' %}" title="McCarthy Code"></a>
      <ul class="profiles navbar-nav">
        <a href="https://www.facebook.com/McCarthyCode">
          <li class="nav-item"><i class="fab fa-facebook" title="Facebook" target="_blank"></i></li>
        </a>
        <a href="https://github.com/McCarthyCode">
          <li class="nav-item"><i class="fab fa-github" title="GitHub" target="_blank"></i></li>
        </a>
        <a href="https://www.linkedin.com/in/McCarthyCode">
          <li class="nav-item"><i class="fab fa-linkedin" title="LinkedIn" target="_blank"></i></li>
        </a>
        <a href="https://stackoverflow.com/users/2858094/matt-mccarthy?tab=profile">
          <li class="nav-item"><i class="fab fa-stack-overflow" title="Stack Overflow" target="_blank"></i></li>
        </a>
      </ul>
      <button id="navbarMenuButton" class="d-lg-none" type="button">
        <i class="fas fa-bars"></i>
      </button>
      <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <a class="nav-link" href="{% url 'home:index' %}">
            <li class="nav-item">Home/Contact</li>
          </a>
          <a class="nav-link" href="{% url 'home:about' %}">
            <li class="nav-item">About</li>
          </a>
          <a class="nav-link" href="{% url 'home:portfolio' %}">
            <li class="nav-item">Portfolio</li>
          </a>
          <a class="nav-link" href="mailto:info@mccarthycode.com">
            <li class="nav-item"><span class="text-nowrap">Request a Quote</span></li>
          </a>
          {% if request.user.is_superuser %}
          <a class="nav-link" href="{% url 'home:dashboard' %}">
            <li class="nav-item">Dashboard</li>
          </a>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>