home/urls.py
from django.urls import re_path

from . import views
from mwd.settings import STAGE

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^login/$', views.login_view, name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^portfolio/$', views.portfolio, name='portfolio'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    re_path(r'^sites/$', views.sites, name='sites'),
    re_path(r'^sites/reorder/$', views.reorder_sites, name='reorder-sites'),
    re_path(r'^sites/add/$', views.add_site, name='add-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/edit/$', views.edit_site, name='edit-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete/$', views.delete_site, name='delete-site'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete-screenshot/(?P<screenshot_id>[1-9]\d*)/$', views.delete_screenshot, name='delete-screenshot'),
    re_path(r'^sites/(?P<site_id>[1-9]\d*)/delete-screenshots/$', views.delete_screenshots, name='delete-screenshots'),
]

if STAGE != 'production':
    urlpatterns += [
        re_path(r'^400/$', views.view_400),
        re_path(r'^403/$', views.view_403),
        re_path(r'^404/$', views.view_404),
        re_path(r'^500/$', views.view_500),
    ]

mwd/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500,
)
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^legal/', include(('legal.urls', 'legal'), namespace='legal')),
    re_path(r'^quote/', include(('quotes.urls', 'quotes'), namespace='quotes')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'home.views.view_400'
handler403 = 'home.views.view_403'
handler404 = 'home.views.view_404'
handler500 = 'home.views.view_500'

quotes/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^manager/$', views.manager, name='manager'),
    re_path(r'^delete/(?P<quote_id>[1-9]\d*)/$', views.delete, name='delete'),
]

home/forms.py
from django import forms

from .models import Site

class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(BaseForm, self).__init__(*args, **kwargs)

class BaseModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  # globally override the Django >=1.6 default of ':'
        super(BaseModelForm, self).__init__(*args, **kwargs)

class SiteForm(BaseModelForm):
    name = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Site Name',
        }),
    )
    url = forms.CharField(
        label='',
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'URL',
        }),
    )
    github = forms.CharField(
        label='',
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'value': 'https://github.com/McCarthyCode/',
            'placeholder': 'GitHub URL',
        }),
    )
    active = forms.BooleanField(
        initial=True,
        required=False,
        label='Website Is Active',
        widget=forms.CheckboxInput()
    )
    description = forms.CharField(
        label='',
        max_length=200,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Description',
            'rows': 5,
        }),
    )
    screenshots = forms.ImageField(
        label='Screenshots',
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )

    def clean(self):
        super().clean()
        return self.cleaned_data

    class Meta:
        model = Site
        fields = ['name', 'url', 'github', 'active', 'description']

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import (
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseRedirect,
)
from django.shortcuts import render, redirect, reverse, get_object_or_404

from .forms import SiteForm
from .models import Site, Screenshot
from .recaptcha import verify_v3

def view_400(request, exception=None):
    return render(request, 'errors/400.html', status=400)

def view_403(request, exception=None):
    return render(request, 'errors/403.html', status=403)

def view_404(request, exception=None):
    return render(request, 'errors/404.html', status=404)

def view_500(request, exception=None):
    return render(request, 'errors/500.html', status=500)

def index(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/index.html')

def legal(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'legal/index.html')

def login_view(request):
    if request.method == 'GET':
        if request.user.is_superuser:
            messages.info(request, 'You are already logged in. You have been redirected to the dashboard.')

            return redirect('home:dashboard')

        return render(request, 'home/login.html')
    elif request.method == 'POST':
        api_response = verify_v3(request)
        api_response_content = json.loads(str(api_response.content, encoding='utf-8'))

        if not api_response_content['success'] or api_response.status_code != 200:
            messages.error(request, 'There was an error with reCAPTCHA v3.')

            return redirect('quotes:index')

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)

            messages.success(request, 'Welcome, %s!' %
                (user.first_name if user.first_name else user.username)
            )

            return redirect('home:dashboard')
        else:
            messages.error(request, 'There was an error logging in with that username/password combination.')

            return redirect('home:login')
    else:
        return HttpResponseBadRequest()

def logout_view(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    logout(request)

    messages.success(request, 'You have successfully logged out.')

    return redirect('home:login')

def portfolio(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    sites = []
    for site in Site.objects.all().order_by('order'):
        sites.append({
            'data': site,
            'screenshots': Screenshot.objects.filter(site=site).order_by('date_updated'),
        })

    return render(request, 'home/portfolio.html', {'sites': sites})

def about(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/about.html')

def dashboard(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/dashboard.html')

def sites(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/sites.html', {
        'sites': Site.objects.all().order_by('order'),
    })

def reorder_sites(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'POST':
        return HttpResponseBadRequest()

    order = json.loads(request.POST.get('order'))

    position = 0
    for site_id in order:
        site = get_object_or_404(Site, id=site_id)
        if site.order != position:
            site.order = position
            site.save()
        position += 1

    return render(request, 'home/sites.html', {
        'sites': Site.objects.all().order_by('order'),
    })

def add_site(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == 'GET':
        return render(request, 'home/add_site.html', {
            'form': SiteForm(),
        })
    elif request.method == 'POST':
        form = SiteForm(request.POST, request.FILES)

        if form.is_valid():
            site = form.save()

            for image in request.FILES.getlist('screenshots'):
                screenshot = Screenshot.create(image=image, site=site)
                screenshot.save()

            messages.success(request, 'You have successfully added "%s."' % site.name)

            return redirect('home:sites')

        messages.error(request, 'There was an error adding a site.')

        return redirect('home:add-site')

    return HttpResponseBadRequest()

def edit_site(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    site = get_object_or_404(Site, id=site_id)

    if request.method == 'GET':
        return render(request, 'home/edit_site.html', {
            'site': site,
            'screenshots': Screenshot.objects.filter(site=site).order_by('date_updated'),
            'form': SiteForm(instance=site),
        })
    elif request.method == 'POST':
        form = SiteForm(request.POST, request.FILES, instance=site)

        if form.is_valid():
            site = form.save()

            order = json.loads(request.POST.get('order'))

            for screenshot_id in order:
                screenshot = get_object_or_404(Screenshot, id=screenshot_id)
                screenshot.save()

            for image in request.FILES.getlist('screenshots'):
                screenshot = Screenshot.create(image=image, site=site)
                screenshot.save()

            messages.success(request, 'You have successfully edited "%s."' % site.name)

            return redirect('home:sites')

        messages.error(request, 'There was an error editing the site.')

        return HttpResponseRedirect(
            reverse('home:edit-site', args=[site_id])
        )

    return HttpResponseBadRequest()

def delete_site(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    site.delete()

    messages.success(request, 'You have successfully deleted "%s" and its corresponding screenshots.' % site.name)

    return redirect('home:sites')

def delete_screenshot(request, site_id, screenshot_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    screenshot = get_object_or_404(Screenshot, id=screenshot_id)

    assert site == screenshot.site

    screenshot.delete()

    messages.success(request, 'Screenshot successfully deleted.')

    return HttpResponseRedirect(
        reverse('home:edit-site', args=[site_id])
    )

def delete_screenshots(request, site_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    site = get_object_or_404(Site, id=site_id)
    site.delete_screenshots()

    messages.success(request, 'Screenshots successfully deleted.')

    return HttpResponseRedirect(
        reverse('home:edit-site', args=[site_id])
    )

home/templates/home/about.html
{% extends 'home/base.html' %}{% load static %}

{% block content %}
<section id="about" class="page">
  <div class="container">
    <h1 class="h1">{% block title %}About{% endblock %} Matt McCarthy and <span class="brand"></span></h1>
    <div class="body">
      <div class="img-container float-md-left d-inline-block">
        <a data-fancybox="gallery" href="{% static 'home/img/profile.png' %}">
          <img src="{% static 'home/img/profile_thumbnail.png' %}">
        </a>
      </div>
      <p>
        <a href="{% static 'home/img/general_kenobi.png' %}" title="General Kenobi!">Hello, there!</a>
      </p>
      <p>
        My name is Matt McCarthy and I am a full stack Web and mobile app developer. I completed coursework at the University of Illinois at Chicago (UIC) and graduated from the Coding Dojo, a 14-week bootcamp. My hobbies include <a class="external-link" href="http://www.coastercounter.com/mattmc318">scoring rollercoaster credits</a>, singing karaoke (mostly alt-rock and classic rock), and tinkering with Linux systems. Ever since the days of MySpace and the transition from dial-up to broadband Internet, I have been constantly intrigued by how computers and the Web have worked, and have always made an effort to understand new technologies as best I could. As a middle school student, I would analyze HTML code copy-and-pasted to my MySpace page, and would use Web resources to build my first, rudimentary Web page.
      </p>
      <p>
        During my time at UIC (2011&ndash;2014), I majored in computer science and upheld an A average in my major coursework. While there, I was a member of the robotics team in the school's <abbr title="Institute of Electrical and Electronics Engineers">IEEE</abbr> chapter. At the University of Illinois Urbana-Champaign (UIUC), I competed in both the Jerry Sanders Design Competition (JSDC), a robotics competition, and HackIllinois (also at UIUC), a software and hardware hackathon. At HackIllinois, I was a top-10 finalist in the hardware category, with roughly 200 contestants total at the time. Along with one other UIC student and IEEE robotics member, I designed and built <a class="external-link" href="https://devpost.com/software/redbull-robot-checkers-player">a robotic arm</a> using empty RedBull cans, a few servos, and an Electric Imp (<abbr title="Internet of Things">IoT</abbr>-connected processor). I chose not to finish my degree due to financial constraints in conjunction with a years-long period of struggle with medical issues, which I eventually overcame.
      </p>
      <div class="img-container float-md-right d-inline-block">
        <a data-fancybox="gallery" href="{% static 'home/img/RBR.jpg' %}">
          <img src="{% static 'home/img/RBR_thumbnail.jpg' %}">
        </a>
      </div>
      <p>
        From 2017 to 2018, I ended my educational hiatus by attending coursework at the Coding Dojo, where I reviewed Web fundamentals (HTML, CSS, JavaScript/jQuery) and learned three new software stacks: Django, .NET, and <abbr title="Mongo DB, Express.js, Angular, & Node.js">MEAN</abbr>. Of the three, I strongly favored Django due to Python's syntactic ease and Django's core framework. It was upon graduating from the bootcamp that I decided to program in Python under Django full-time as a freelance developer, and thus <span class="brand"></span> (MC), known then as McCarthy Web Design, was born.
      </p>
      <p>
        It took months of constant preparations, but before the end of the year, I was able to land my first client, Coolwater Creations (CWC), under the name McCarthy Web Design. This was not my first-ever client&mdash;I had been hired in 2014 for Susan Kill Kegan & Associates (SKK&A) using a PHP back-end&mdash;but it was my first paid project using a more organized, streamlined <a class="external-link" href="https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">MVC framework</a>. Later, I would design, develop, and host five more sites, including a redesign of SKK&A and the site you are viewing right now. All of these sites are available to view on <a href="{% url 'home:portfolio' %}">the portfolio page</a>.
      </p>
      <p>
        In my business, and in all my computing practices, I adhere to <a class="external-link" href="https://en.wikipedia.org/wiki/KISS_principle">the KISS principle ("Keep it simple, stupid!")</a>. For all of my sites, this may mean more whitespace, vibrant, yet subdued color palettes, and basic functionality tied together in a way that is still appealing and functional to administrators and end users alike. I am constantly learning how to keep my software <a class="external-link" href="https://en.wikipedia.org/wiki/Don%27t_repeat_yourself">DRY ("Don't repeat yourself")</a>, and have improved on this concept quite a bit over the years, allowing myself to become a faster and more efficient developer.
      </p>
      <p>
        To learn more about me, <span class="brand"></span>, or how to obtain a site for yourself, check out <a href="{% url 'home:index' %}#contact">the contact page</a>. Thank you for taking the time to read about me and my business!
      </p>
      <p>
        Best,<br>
        Matt
      </p>
    </div>
  </div>
</section>
{% endblock %}

home/templates/home/dashboard.html
{% extends 'home/base.html' %}

{% block content %}
<section class="page">
  {% if messages %}
  <div class="container">
    {% include 'home/messages.html' %}
  </div>
  {% endif %}
  <div class="container max-w-320px">
    <h1 class="h1">{% block title %}Dashboard{% endblock %}</h1>
    <div class="card">
      <h2 class="h2">Manage:</h2>
      <ul class="ul">
        <li><a href="{% url 'home:sites' %}{% comment %}
          Change to: {% url 'sites:manager' %}{% endcomment %}">Sites</a></li>
        <li><a href="{% url 'quotes:manager' %}">Quote Requests</a></li>
        {# <li><a href="{% url 'quotes:contacts' %}">Contacts</a></li> #}
      </ul>
    </div>
  </div>
</section>
{% endblock %}

home/templates/home/edit_site.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Edit {{ site.name }}{% endblock %}

{% block js %}
<!-- Home App JS -->
<script src="{% static 'home/js/reorder_screenshots.min.js' %}"></script>
<script src="{% static 'home/js/edit_sites.min.js' %}"></script>
{% endblock %}

{% block content %}
<section id="edit_site" class="page">
  {% if messages %}
  <div class="container">
    {% include 'home/messages.html' %}
  </div>
  {% endif %}
  <div class="container max-w-480px">
    <form method="POST" enctype="multipart/form-data">
      <h1 class="h1">Edit Site</h1>
      <h2 class="h2">{{ site.name }}{% if not site.active %} <em class="inactive">(Defunct)</em>{% endif %}</h2>
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form.visible_fields %}
      {{ field.errors }}
      {% if field.name == 'active' %}
      {% include 'fields/custom_checkbox.html' with field=form.active %}
      {% else %}
      {% if field.name == 'screenshots' %}
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% endif %}
      {{ field }}
      {% endif %}
      {% endfor %}
      <input type="hidden" name="order" value="[{% for screenshot in screenshots %}{{ screenshot.id}}{% if screenshot != screenshots|last %}, {% endif %}{% endfor %}]">
      {% if screenshots %}
      <a id="delete_screenshots" class="btn btn-danger" href="{% url 'home:delete-screenshots' site.id %}">Delete All</a>
      <button id="toggle_screenshots" class="btn btn-secondary">
        <span>Show</span> Screenshots <i class="fas fa-chevron-down"></i>
      </button>
      <ul class="screenshot-list">
        {% for screenshot in screenshots %}
        <li data-id="{{ screenshot.id }}">
          <div class="controls">
            <i class="fas fa-caret-up fa-3x"></i>
            <i class="fas fa-caret-down fa-3x"></i>
          </div>
          <div class="thumbnail-container">
            <a data-fancybox="gallery" href="{{ screenshot.image.url }}">
              <img src="{{ screenshot.thumbnail.url }}" alt="Thumbnail">
            </a>
          </div>
          <div class="btn-container">
            <a href="{% url 'home:delete-screenshot' site.id screenshot.id %}" class="btn btn-danger">Delete</a>
          </div>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      <input class="btn btn-primary form-control" type="submit" value="Submit">
    </form>
  </div>
</section>
{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %} {% load static %} {% block title %}Home and
Contact{% endblock %} {% block js %}
<!-- Home App JS -->
<script src="{% static 'home/js/index.min.js' %}"></script>
{% endblock %} {% block content %}
<div id="index">
  <header>
    <h1 class="h1 text-nowrap brand"></h1>
    <div class="container">
      <div class="card">
        <img src="{% static 'global/img/favicon.png' %}" alt="MC Logo" />
        <div>
          <h2 class="h2">
            Professional, Fully Featured Web Sites and Mobile Apps
          </h2>
          <h3 class="h3">Billed hourly</h3>
          <a class="btn btn-primary form-control" href="mailto:info@mccarthycode.com">
            Request a Free Quote
          </a>
        </div>
      </div>
    </div>
    <button class="chevron text-center">
      <i class="fas fa-chevron-down"></i>
    </button>
  </header>
  <section id="icons">
    <div class="container">
      <ul id="options">
        <li>
          <a href="{% url 'home:about' %}">
            <button tabindex="-1">
              <i class="fas fa-address-card fa-5x"></i>
            </button>
            <label class="text-center">About</label>
          </a>
        </li>
        <li>
          <a href="{% url 'home:portfolio' %}">
            <button tabindex="-1">
              <i class="fas fa-book-open fa-5x"></i>
            </button>
            <label class="text-center">Portfolio</label>
          </a>
        </li>
        <li>
          <a href="javascript:void(0);">
            <button tabindex="-1">
              <i class="fas fa-mobile-alt fa-5x"></i>
            </button>
            <label class="text-center">Contact</label>
          </a>
        </li>
      </ul>
    </div>
    <button class="chevron text-center">
      <i class="fas fa-chevron-down"></i>
    </button>
  </section>
  <section id="contact">
    <div>
      <h2 class="h2">Contact</h2>
      <h3 class="h3">Matt McCarthy</h3>
      <h4 class="h4">Full Stack Developer</h4>
      <ul>
        <li>
          <a href="mailto:info@mccarthycode.com">info@mccarthycode.com</a>
        </li>
        <li>
          <a
            class="external-link"
            href="https://www.google.com/maps/place/Rogers+Park,+Chicago,+IL"
            >Rogers Park, Chicago, IL</a
          >
        </li>
      </ul>
    </div>
  </section>
</div>
{% endblock %}

home/templates/home/privacy.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
<div class="legal">
  <div class="container">
    <section id="privacy">
      <h1 class="h1">Privacy Policy for McCarthy Web Design</h1>

      <p>At McCarthy Web Design, accessible from <a href="{% url 'home:index' %}">https://mccarthywebdesign.com</a>, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by McCarthy Web Design and how we use it.</p>
      <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>

      <h4 class="h4">General Data Protection Regulation (GDPR)</h4>

      <p>We are a Data Controller of your information.</p>
      <p>McCarthy Web Design legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:</p>
      
      <ul class="ul">
        <li>McCarthy Web Design needs to perform a contract with you</li>
        <li>You have given McCarthy Web Design permission to do so</li>
        <li>Processing your personal information is in McCarthy Web Design legitimate interests</li>
        <li>McCarthy Web Design needs to comply with the law</li>
      </ul>
        
      <p>McCarthy Web Design will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.</p> 
      <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. If you wish to be informed what Personal Information we hold about you and if you want it to be removed from our systems, please contact us. Our Privacy Policy was generated with the help of <a class="external-link" href="https://www.gdprprivacypolicy.net/">GDPR Privacy Policy Generator</a> and the <a class="external-link" href="https://www.app-privacy-policy.com/app-privacy-policy-generator/">App Privacy Policy Generator</a>.</p>
      <p>In certain circumstances, you have the following data protection rights:</p>

      <ul class="ul">
        <li>The right to access, update or to delete the information we have on you.</li>
        <li>The right of rectification.</li> 
        <li>The right to object.</li>
        <li>The right of restriction.</li>
        <li>The right to data portability</li>
        <li>The right to withdraw consent</li>
      </ul>

      <h4 class="h4">Log Files</h4>

      <p>McCarthy Web Design follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>

      <h4 class="h4">Cookies and Web Beacons</h4>

      <p>Like any other website, McCarthy Web Design uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>
      <p>For more general information on cookies, please read <a class="external-link" href="https://www.cookieconsent.com/what-are-cookies/">"What Are Cookies."</a></p>

      <h4 class="h4">Privacy Policies</h4>

      <p>You may consult this list to find the Privacy Policy for each of the advertising partners of McCarthy Web Design.</p>
      <p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on McCarthy Web Design, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>
      <p>Note that McCarthy Web Design has no access to or control over these cookies that are used by third-party advertisers.</p>

      <h4 class="h4">Third Party Privacy Policies</h4>

      <p>McCarthy Web Design's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>
      <p>You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>

      <h4 class="h4">Children's Information</h4>

      <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>
      <p>McCarthy Web Design does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>

      <h4 class="h4">Online Privacy Policy Only</h4>

      <p>Our Privacy Policy created at GDPRPrivacyPolicy.net) applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in McCarthy Web Design. This policy is not applicable to any information collected offline or via channels other than this website. <a class="external-link" href="https://gdprprivacypolicy.net">Our GDPR Privacy Policy</a> was generated from the GDPR Privacy Policy Generator.</p>

      <h4 class="h4">Consent</h4>

      <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>
    </section>
  </div>
</div>
{% endblock %}

home/templates/home/sites.html
{% extends 'home/base.html' %} {% load static %} {% block js %}
<!-- Home App JS -->
<script src="{% static 'home/js/reorder_sites.min.js' %}"></script>
{% endblock %} {% block content %}
<section id="sites" class="page">
  {% if messages %}
  <div class="container">{% include 'home/messages.html' %}</div>
  {% endif %}
  <div class="container max-w-480px">
    <div class="header">
      <h1 class="h1">{% block title %}Edit Sites{% endblock %}</h1>
      <div class="btn-container">
        <button class="btn btn-secondary" form="reorder_sites">Reorder</button>
        <a class="btn btn-primary" href="{% url 'home:add-site' %}">Add Site</a>
      </div>
    </div>
    <ul class="sites-list">
      {% for site in sites %}
      <li data-id="{{ site.id }}">
        <div class="controls">
          <i class="fas fa-caret-up fa-3x"></i>
          <i class="fas fa-caret-down fa-3x"></i>
        </div>
        <div class="content">
          <h2 class="h2 text-center">{{ site.name }}{% if not site.active %} <em class="inactive">(Defunct)</em>{% endif %}</h2>
          <div class="btn-container text-center">
            <a
              class="btn btn-secondary"
              href="{% url 'home:edit-site' site.id %}"
            >
              Edit
            </a>
            <a
              class="btn btn-danger"
              href="{% url 'home:delete-site' site.id %}"
            >
              Delete
            </a>
          </div>
        </div>
      </li>
      {% empty %}
      <li class="empty"><em>No sites to display.</em></li>
      {% endfor %}
    </ul>
  </div>
</section>
<form id="reorder_sites" action="{% url 'home:reorder-sites' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="order" />
</form>
{% endblock %}