mwd/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf import settings
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500,
)
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^legal/', include(('legal.urls', 'legal'), namespace='legal')),
    re_path(r'^quote/', include(('quotes.urls', 'quotes'), namespace='quotes')),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'home.views.view_400'
handler403 = 'home.views.view_403'
handler404 = 'home.views.view_404'
handler500 = 'home.views.view_500'

quotes/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^manager/$', views.manager, name='manager'),
    re_path(r'^delete/(?P<quote_id>[1-9]\d*)/$', views.delete, name='delete'),
]

quotes/models.py
from django.db import models
from home.models import TimestampedModel

class Contact(TimestampedModel):
    title_choices = [
        (0, 'Mx.'),
        (1, 'Ms.'),
        (2, 'Mrs.'),
        (3, 'Mr.'),
        (4, 'Dr.'),
    ]

    title = models.PositiveSmallIntegerField(choices=title_choices)
    first_name = models.CharField(max_length=35)
    last_name = models.CharField(max_length=70)
    surname_first = models.BooleanField()
    phone = models.CharField(max_length=10)
    email = models.EmailField(max_length=100)

    @property
    def display_phone(self):
        return '%s %s %s' % (
            self.phone[:3], self.phone[3:6], self.phone[6:]
        )

class QuoteRequest(TimestampedModel):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    description = models.TextField(max_length=500)

quotes/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from .models import Contact, QuoteRequest
from home.widgets import CustomSelect
from mwd.settings import PHONE_REGEX

class QuoteRequestForm(forms.ModelForm):
    title = forms.TypedChoiceField(
        coerce=int,
        label='',
        choices=Contact.title_choices,
        widget=CustomSelect(
            attrs={
                'class': 'form-control',
                'data-label': 'Title',
            },
        ),
    )
    first_name = forms.CharField(
        label='',
        max_length=35,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'First Name',
        }),
    )
    last_name = forms.CharField(
        label='',
        max_length=70,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Last Name',
        }),
    )
    surname_first = forms.BooleanField(
        required=False,
        label='Surname Is First',
        widget=forms.CheckboxInput(),
    )
    phone = forms.CharField(
        label='',
        max_length=20,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Phone',
        }),
        validators=[RegexValidator(PHONE_REGEX, 'Enter a valid U.S. phone number.')],
    )
    email = forms.EmailField(
        label='',
        max_length=200,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email',
        }),
    )
    description = forms.CharField(
        label='',
        required=False,
        max_length=500,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Summary of Site/App Contents (optional)\nBe as detailed or as general as you like.',
            'rows': 6,
        }),
    )

    def clean(self):
        super().clean()
        cleaned_data = self.cleaned_data

        try:
            cleaned_data['phone'] = PHONE_REGEX.sub(
                r'\2\3\4', cleaned_data['phone']
            )
        except KeyError:
            # 'phone' not in cleaned_data.
            # Error handled in RegexValidator.
            return cleaned_data

        # Retrieve contact first by email, then by phone number.
        # If successful, update. Otherwise, create new.
        kwargs = {
            'title': cleaned_data['title'],
            'first_name': cleaned_data['first_name'],
            'last_name': cleaned_data['last_name'],
            'surname_first': cleaned_data['surname_first'],
        }

        try:
            contact = Contact.objects.get(email=cleaned_data['email'])

            kwargs['phone'] = cleaned_data['phone']
            for key, value in kwargs.items():
                setattr(contact, key, value)

            contact.save()
        except Contact.DoesNotExist:
            try:
                contact = Contact.objects.get(phone=cleaned_data['phone'])

                kwargs['email'] = cleaned_data['email']
                for key, value in kwargs.items():
                    setattr(contact, key, value)

                contact.save()
            except Contact.DoesNotExist:
                contact = Contact.objects.create(
                    phone=cleaned_data['phone'],
                    email=cleaned_data['email'],
                    **kwargs
                )

        cleaned_data['contact'] = contact

        return cleaned_data

    class Meta:
        model = QuoteRequest
        fields = [
            'title', 'first_name', 'last_name', 'surname_first',
            'phone', 'email', 'description',
        ]

quotes/views.py
import json

from django.contrib import messages
from django.http import (
    HttpResponseBadRequest,
    HttpResponseForbidden,
)
from django.shortcuts import render, redirect, get_object_or_404

from .forms import QuoteRequestForm
from .models import QuoteRequest
from home.recaptcha import verify_v2

def index(request):
    if request.method == 'GET':
        return render(request, 'quotes/index.html', {
            'form': QuoteRequestForm(),
        })
    elif request.method == 'POST':
        api_response = verify_v2(request)
        api_response_content = json.loads(str(api_response.content, encoding='utf-8'))

        if not api_response_content['success'] or api_response.status_code != 200:
            messages.error(request, 'There was an error submitting the form.')
            messages.error(request, 'Please prove you are human by checking the checkbox labeled "I\'m not a robot" and possibly completing a security challenge.')

            return render(request, 'quotes/index.html', {'form': form})

        form = QuoteRequestForm(request.POST)

        if form.is_valid():
            quote_request = form.save(commit=False)

            quote_request.contact = form.cleaned_data['contact']
            quote_request.save()

            messages.success(request, b'Thank you for submitting a quote request. McCarthy Code\xe2\x84\xa2 will contact you via phone or email within 1-3 business days.'.decode("UTF-8"))

            return redirect('quotes:index')

        messages.error(request, 'There was an error submitting the form.')

        return render(request, 'quotes/index.html', {
            'form': form,
        })

    return HttpResponseBadRequest()

def manager(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'quotes/manager.html', {
        'quote_requests': QuoteRequest.objects.all().order_by('date_created')
    })

def delete(request, quote_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method != 'GET':
        return HttpResponseBadRequest()

    quote_request = get_object_or_404(QuoteRequest, id=quote_id)
    quote_request.delete()

    messages.success(request, 'You have successfully deleted the quote request.')

    return redirect('quotes:manager')

quotes/templates/quotes/index.html
{% extends 'home/base.html' %}

{% block js %}  <!-- reCAPTCHA v2 JS -->
  <script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block content %}
<section class="page">
  {% if messages %}
  <div class="container">
    {% include 'home/messages.html' %}
  </div>
  {% endif %}
  <div class="container max-w-480px">
    <form method="POST">
      <h1 class="h1">{% block title %}Request a Quote{% endblock %}</h1>
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form.visible_fields %}
      {% if field.name == 'title' %}
      {{ form.title.errors }}
      {{ form.first_name.errors }}
      {{ form.last_name.errors }}
      {{ form.surname_first.errors }}
      <div class="name">
        {{ form.title }}
        {{ form.first_name }}
        {{ form.last_name }}
        {{ form.surname_first.widget }}
        {% include 'fields/custom_checkbox.html' with field=form.surname_first %}
      </div>
      {% elif field.name != 'first_name' and field.name != 'last_name' and field.name != 'surname_first' %}
      {{ field.errors }}
      {{ field }}
      {% endif %}
      {% endfor %}
      <div class="g-recaptcha-container">
        <div class="g-recaptcha"
          data-sitekey="{{ reCAPTCHA_v2_site_key }}"
          data-theme="dark"></div>
      </div>
      <input class="btn btn-primary form-control" type="submit" value="Submit Request">
    </form>
  </div>
</section>
{% endblock %}

quotes/templates/quotes/manager.html
{% extends 'home/base.html' %}

{% block content %}
<section class="page">
  <div class="container">
    {% include 'home/messages.html' %}
    <h1 class="h1">{% block title %}Quote Request Manager{% endblock %}</h1>
    <ul class="grid">
      {% for quote_request in quote_requests %}
      <li class="card">
        <a class="close float-right" href="{% url 'quotes:delete' quote_request.id %}">&times;</a>
        <h2 class="h2">{{ quote_request.contact.get_title_display }} {{ quote_request.contact.first_name }} {{ quote_request.contact.last_name }}</h2>
        <h3 class="h3">{{ quote_request.date_created|date:"N j g:i a" }}</h3>
        <p><a href="tel:+1{{ quote_request.contact.phone }}">{{ quote_request.contact.display_phone }}</a></p>
        <p><a href="mailto:{{ quote_request.contact.email }}?subject=Thank+you+for+your+interest+in+McCarthy+Code!&body=">{{ quote_request.contact.email }}</a></p>
        {% if quote_request.description %}
        {{ quote_request.description|linebreaks }}
        {% endif %}
      </li>
      {% empty %}
      <li class="empty"><em>No requests to display.</em></li>
      {% endfor %}
    </ul>
  </div>
</section>
{% endblock %}